### ISSUE TITLE
publish this on npm

### ISSUE THREAD

**Issue by mreinstein** [RonenNess/SSCD.js#2]
would be great to package this with npm, and have it available here: https://www.npmjs.com/search?q=sscd

looks like `sscd` is available as a package name. :)

**Comment by mreinstein** [comment]
this should probably be done after wrapping in UMD format #1

**Comment by RonenNess** [comment]
Hi mreinstein, 

I'll look into it, if its simple enough to make it npm compliance I'll do it.
Thanks :)

**Comment by RonenNess** [comment]
done.
https://www.npmjs.com/package/sscd

thanks!
