### ISSUE TITLE
separate the rendering code from physics

### ISSUE THREAD

**Issue by mreinstein** [RonenNess/SSCD.js#3]
I noticed that all of the shapes have a render function built-in. I think it would be cleaner to have this outside of the physics objects. (i.e., I'm considering using this in my game, but I already have all my own drawing functions.)

**Comment by RonenNess** [comment]
Hi mreinstein,
I have mixed feelings about this issue - basically you are right but I kind of like the shape.render(ctx) api. its very elegant. I can, however, add those functions to the shapes prototype from a different source file. what do you think about that?

**Comment by RonenNess** [comment]
Hi,
Eventually I decided to leave it as it is. To use customized rendering functions you can override the render() functions, or simply not use them.

thanks anyway :)

**Comment by mreinstein** [comment]
> To use customized rendering functions you can override the render() functions, or simply not use them.

the name of the project is "super simple collision detection". bundling rendering functions that assume people are drawing to canvas is not super simple. I'd really urge building things more modularly. there are tons of half-baked javascript game engines out there. SSCD can set itself apart by being true to it's name and stripping out the non-physics bits. That's what most people came here for, IMO.

I realize this is your library and you're certainly free to do with it as you wish, just my 2 cents as a user. :)

anyway, thanks for the interesting code! worth looking at.

**Comment by RonenNess** [comment]
thanks for the feedback, I just wanted to add that rendering is for debug purposes only (I hope its clear enough from the docs), so I don't feel like its turning sscd into a half-baked game engine. I could use an external debug renderer the user need to implement with functions like "draw rectangle" "draw lines" etc (like in box2d did in C++) but that would have make sscd slightly less simple. 

PS did you see I put it on npm? still looking into the UMD wrapper.

thanks :)
