### ISSUE TITLE
Doesn't handle rotated objects properly

### ISSUE THREAD

**Issue by ChrisKatsaras** [RonenNess/SSCD.js#4]
Perhaps I am misunderstanding but it seems that there isn't a way to set the rotation of an object. 
e.g checking to see if a rotated rectangle collides with another rectangle.

**Comment by RonenNess** [comment]
Rotation is not supported.. I was planning on adding it one day but ended up deserting this project before I did. If you end up writing rotation support yourself feel free to open a PR. Or maybe there are other libs that have it out of the box, I would check.

Thanks,
